name: Build

on:
  workflow_dispatch:
  push:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          submodules: 'recursive'

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - uses: seanmiddleditch/gha-setup-ninja@master
        with:
          version: 1.12.0

      - name: Build
        run: |
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses > /dev/null
          
          rm -rf $ANDROID_HOME/cmake
          ./gradlew :core:publishToMavenLocal
